apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: quobyte-csi-dynamic-provisioning-upstream-e2e
# provisioner must match CSI_PROVISIONER_NAME in this directory's "env" file
provisioner: csi.quobyte.com
allowVolumeExpansion: true
parameters:
  # must match QUOBYTE_TENANT in this directory's "env" file
  quobyteTenant: "My Tenant"
  csi.storage.k8s.io/provisioner-secret-name: "quobyte-admin-credentials"
  csi.storage.k8s.io/provisioner-secret-namespace: "quobyte"
  csi.storage.k8s.io/controller-expand-secret-name: "quobyte-admin-credentials"
  csi.storage.k8s.io/controller-expand-secret-namespace: "quobyte"
  csi.storage.k8s.io/node-publish-secret-name: "quobyte-admin-credentials"
  csi.storage.k8s.io/node-publish-secret-namespace: "quobyte"
  createQuota: "true"
reclaimPolicy: Delete
