apiVersion: v1
kind: Pod
metadata:
  name: nginx-pre-provisioned-snapshot-vol
spec:
  containers:
  - name: server
    image: nginx:1.14
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: quobytepvc
  volumes:
    - name: quobytepvc
      persistentVolumeClaim:
        claimName: restore-snapshot-pvc-pre-provisioned