kind: PersistentVolume
apiVersion: v1
metadata:
  name: preprovisoned-quobyte-csi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # Delete Reclaim policy does not work with CSI for pre-provisioned volumes
  persistentVolumeReclaimPolicy: Retain
  # use mountOptions: - ro to mount the volume represented by this PV as read-only.
  # kubernetes has few places where this can be configured but some of those
  # settings do not reach Quobyte CSI. 
  # If volume needs to be mounted into particular pod as readonly then
  # use VolumeMounts.readOnly as shown in the example here:
  # https://kubernetes.io/docs/concepts/storage/volumes/#example-pod-with-a-secret-a-downward-api-and-a-configmap
  # mountOptions:
  #   - ro
  storageClassName: quobyte-csi
  csi:
    driver: csi.quobyte.com
    # VolumeHandle should be of the format <TENANT_UUID/NAME>|<VOLUME_UUID/NAME> or 
    #  <TENANT_UUID/NAME>|<VOLUME_UUID/NAME>|sub-directory
    # VolumeHandle can be '|VOLUME_UUID' or
    # VolumeHandle: '|VOLUME_UUID|config' mounts the config sub-directory under
    # volume with the specified UUID
    volumeHandle: "My Tenant|test"
    # nodePublishSecretRef is required only if you use volume name in volumeHandle.
    # Example volumeHandle: <TENANT_NAME>|<VOLUME_NAME>
    nodePublishSecretRef:
      name: quobyte-admin-credentials
      namespace: quobyte
