# If kubectl -f create fails with the following error
# no matches for kind "..." in version ".../v1beta1"
# please try with snapshot.storage.k8s.io/v1
# https://github.com/rook/rook/issues/6819#issuecomment-852059116
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-dynamic-provision
spec:
  volumeSnapshotClassName: quobyte-csi-snapshotclass
  source:
    persistentVolumeClaimName: quobyte-csi-test