apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  # Should match VolumeSnapshotContent.spec.volumeSnapshotRef.name
  # of pre-provisioned VolumeSnapshotContent object
  name: volume-snapshot-pre-provisioned
  # Should match VolumeSnapshotContent.spec.volumeSnapshotRef.namespace
  # of pre-provisioned VolumeSnapshotContent object
  namespace: default
spec:
  source:
    # VolumeSnapshotContent object name
    # Match with the VolumeSnapshotContent.metadata.name
    volumeSnapshotContentName: snapcontent-pre-provisioned 