apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot-dynamic-provision
spec:
  volumeSnapshotClassName: quobyte-csi-snapshotclass
  source:
    persistentVolumeClaimName: quobyte-csi-test