apiVersion: v1
kind: Secret
metadata:
  name: quobyte-api-secret
type: "kubernetes.io/quobyte"
data:
  # base64 encoded values of mount_access_key.csv
  accessKeyId: "TWdUNm41Y1Bqd0hoeTVwZ3V6V2s="
  accessKeySecret: "WHFnd0VhVjduTVB0U2R2YlVtUHNDTWNrdmplNkUvYVZDUjlqbkIyYw=="
