---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: quobyte-csi-controller-sa-csi-quobyte-com
  namespace: kube-system
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quobyte-csi-node-sa-csi-quobyte-com
  namespace: kube-system
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quobyte-csi-pod-killer-sa-csi-quobyte-com
  namespace: kube-system
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-provisioner-role-csi-quobyte-com
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
# Attacher must be able to work with PVs, nodes and VolumeAttachments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-attacher-role-csi-quobyte-com
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-resizer-runner-csi-quobyte-com
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-driver-registrar-role-csi-quobyte-com
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-pod-killer-role-csi-quobyte-com
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get"]
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-provisioner-binding-csi-quobyte-com
subjects:
  - kind: ServiceAccount
    name: quobyte-csi-controller-sa-csi-quobyte-com
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: quobyte-csi-provisioner-role-csi-quobyte-com
  apiGroup: rbac.authorization.k8s.io
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-attacher-binding-csi-quobyte-com
subjects:
  - kind: ServiceAccount
    name: quobyte-csi-controller-sa-csi-quobyte-com
    namespace: kube-system 
roleRef:
  kind: ClusterRole
  name: quobyte-csi-attacher-role-csi-quobyte-com
  apiGroup: rbac.authorization.k8s.io
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role-csi-quobyte-com
subjects:
  - kind: ServiceAccount
    name: quobyte-csi-controller-sa-csi-quobyte-com
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-resizer-runner-csi-quobyte-com
  apiGroup: rbac.authorization.k8s.io
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-driver-registrar-binding-csi-quobyte-com
subjects:
  - kind: ServiceAccount
    name: quobyte-csi-node-sa-csi-quobyte-com
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: quobyte-csi-driver-registrar-role-csi-quobyte-com
  apiGroup: rbac.authorization.k8s.io
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-pod-killer-binding-csi-quobyte-com
subjects:
  - kind: ServiceAccount
    name: quobyte-csi-pod-killer-sa-csi-quobyte-com
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: quobyte-csi-pod-killer-role-csi-quobyte-com
  apiGroup: rbac.authorization.k8s.io
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
apiVersion: v1
kind: Service
metadata:
  name: quobyte-pod-killer-controller
spec:
  selector:
    app.kubernetes.io/name: quobyte-csi-pod-killer-controller-csi-quobyte-com
  ports:
  - name: quobyte pod killer port
    protocol: HTTP
    port: 80
    targetPort: quobyte-pod-killer-port
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: quobyte-csi-node-csi-quobyte-com
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: quobyte-csi-node-csi-quobyte-com
  template:
    metadata:
      labels:
        app: quobyte-csi-node-csi-quobyte-com
        role: quobyte-csi
    spec:
      priorityClassName: system-node-critical
      serviceAccount: quobyte-csi-node-sa-csi-quobyte-com
      hostNetwork: true
      containers:        
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi.quobyte.com /registration/csi.quobyte.com-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.quobyte.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                    fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/        
        - name: quobyte-csi-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/quobyte/csi:v2.0.3
          imagePullPolicy: "IfNotPresent"
          args :
            - "--csi_socket=$(CSI_ENDPOINT)"
            - "--quobyte_mount_path=$(QUOBYTE_MOUNT_PATH)"
            - "--node_name=$(KUBE_NODE_NAME)"
            - "--api_url=$(QUOBYTE_API_URL)"
            - "--driver_name=csi.quobyte.com"
            - "--driver_version=v2.0.3" 
            - "--enable_access_key_mounts=false"
            - "--quobyte_version=3"
            - "--immediate_erase=false"
            - "--use_k8s_namespace_as_tenant=false"
            - "--role=node_driver"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: QUOBYTE_MOUNT_PATH
              value:  /home/quobyte/mounts
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: QUOBYTE_API_URL
              value: http://quobyte-api.default.svc.cluster.local:7860
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: quobyte-mounts
              mountPath: /home/quobyte
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: log-dir
              mountPath: /tmp
            - name: certs
              mountPath: /etc/ssl/certs/        
        - name: quobyte-csi-mount-monitor
          securityContext:
            privileged: true
          image: quay.io/quobyte/pod-killer:v0.1.3
          imagePullPolicy: "IfNotPresent"
          args :
            - "--node_name=$(KUBE_NODE_NAME)"
            - "--service_url=http://quobyte-pod-killer/"
            - "--monitoring_interval=5s"
            - "--role=monitor"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"      
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: quobyte-mounts
          hostPath:
            # Quobyte client also should use the same mount point
            path: /home/quobyte
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            # required by kubernetes CSI
            path: /var/lib/kubelet/plugins/csi.quobyte.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: log-dir
          hostPath:
            path: /tmp
            type: Directory
        - name: certs
          hostPath:
            path: /etc/ssl/certs/
            type: Directory
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: quobyte-csi-controller-csi-quobyte-com
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: quobyte-csi-controller-csi-quobyte-com
  serviceName: quobyte-csi-csi-quobyte-com 
  replicas: 1
  template:
    metadata:
      labels:
        app: quobyte-csi-controller-csi-quobyte-com
        role: quobyte-csi-csi-quobyte-com
    spec:
      priorityClassName: system-cluster-critical
      serviceAccount: quobyte-csi-controller-sa-csi-quobyte-com
      containers:        
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v4.0.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=3"
            - "--extra-create-metadata=true"
            - "--timeout=5m"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/        
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.8.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/        
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.5.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/        
        - name: quobyte-csi-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/quobyte/csi:v2.0.3
          imagePullPolicy: "IfNotPresent"
          args:
            - "--csi_socket=$(CSI_ENDPOINT)"
            - "--quobyte_mount_path=$(QUOBYTE_MOUNT_PATH)"
            - "--node_name=$(KUBE_NODE_NAME)"
            - "--api_url=$(QUOBYTE_API_URL)" 
            - "--driver_name=csi.quobyte.com"
            - "--driver_version=v2.0.3"
            - "--enable_access_key_mounts=false"
            - "--quobyte_version=3"
            - "--immediate_erase=false"
            - "--use_k8s_namespace_as_tenant=false"
            - "--shared_volumes_list="
            - "--role=controller"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: QUOBYTE_MOUNT_PATH
              value:  /home/quobyte/mounts
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: QUOBYTE_API_URL
              value: http://quobyte-api.default.svc.cluster.local:7860 
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: log-dir
              mountPath: /tmp
            - name: quobyte-mounts
              mountPath: /home/quobyte
              mountPropagation: "Bidirectional"
            - name: certs
              mountPath: /etc/ssl/certs/      
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: quobyte-mounts
          hostPath:
            # Quobyte client also should use the same mount point
            path: /home/quobyte
            type: DirectoryOrCreate
        - name: log-dir
          hostPath:
            path: /tmp
            type: Directory
        - name: certs
          hostPath:
            path: /etc/ssl/certs/
            type: Directory
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: quobyte-csi-pod-killer-controller-csi-quobyte-com
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: quobyte-csi-pod-killer-controller-csi-quobyte-com
  serviceName: quobyte-csi-csi-quobyte-com 
  replicas: 1
  template:
    metadata:
      labels:
        app: quobyte-csi-pod-killer-controller-csi-quobyte-com
        role: quobyte-csi-pod-killer-controller-csi-quobyte-com
    spec:
      priorityClassName: system-cluster-critical
      serviceAccount: quobyte-csi-controller-sa-csi-quobyte-com
      containers:        
        - name: quobyte-csi-pod-killer-controller
          image: quay.io/quobyte/pod-killer:v0.1.3
          ports:
            - containerPort: 8080
              name: quobyte-pod-killer-port
          imagePullPolicy: "IfNotPresent"
          args:
            - "--driver_name=csi.quobyte.com"
            - "--role=controller"
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
---
---
# Source: quobyte-csi-driver/templates/csi-driver.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.quobyte.com
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: None
  requiresRepublish: false
  volumeLifecycleModes:
    - Persistent
