apiVersion: v1
kind: Pod
metadata:
  name: nginx-api-and-mount-secret
spec:
  containers:
  - name: server
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: quobytepvc
  volumes:
    - name: quobytepvc
      persistentVolumeClaim:
        claimName: api-and-mount-secret-storage-class-pvc