kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: generic-secret-storage-class-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: generic-secret-storage-class