kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-and-mount-secret-storage-class-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: api-and-mount-secret-storage-class