apiVersion: v1
kind: Secret
metadata:
  name: quobyte-mount-secret
type: "kubernetes.io/quobyte"
data:
  # base64 encoded values of mount_access_key.csv
  accessKeyId: "WHd4N1I0ckFINWJUVVFoTlFlZUo="
  accessKeySecret: "Y1dOMkZrS1ZCcFIxbmd5aytjUzI1QVhuWmdiK3c4WjFySHE4OEhmdQ=="
