apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: api-and-mount-secret-storage-class
provisioner: csi.quobyte.com
allowVolumeExpansion: true
parameters:
  quobyteTenant: "My Tenant"
  # Volume dynamic provision/deletion requires API access keys
  csi.storage.k8s.io/provisioner-secret-name: "quobyte-api-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "default"
  # Resize volume requires API access keys
  csi.storage.k8s.io/controller-expand-secret-name: "quobyte-api-secret"
  csi.storage.k8s.io/controller-expand-secret-namespace: "default"
  # Mounting requires file system/mount secrets
  csi.storage.k8s.io/node-publish-secret-name: "quobyte-mount-secret"
  csi.storage.k8s.io/node-publish-secret-namespace: "default"
  createQuota: "true"
  user: root
  group: root
  accessMode: "777"
reclaimPolicy: Delete