kind: Service
apiVersion: v1
metadata:
  name: quobyte-csi-provisioner
  labels:
    app: quobyte-csi-provisioner
spec:
  selector:
    app: quobyte-csi-provisioner
  ports:
    - name: quobyte-csi-provisioner
      port: 7821

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: quobyte-csi-provisioner
spec:
  serviceName: "quobyte-csi-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: quobyte-csi-provisioner
    spec:
      serviceAccount: quobyte-csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.2.0
          args:
            # --v=5 logs user credentials
            - "--provisioner=quobyte-csi"
            - "--csi-address=$(ADDRESS)"
            - "--v=3"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: quobyte-csi-provisioner
          image: quay.io/quobyte/csi:v0.2.0
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--quobytemountpath=$(QUOBYTE_MOUNT_PATH)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: QUOBYTE_MOUNT_PATH
              value:  /mnt/quobyte/mounts
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}