#!/bin/bash

CLUSTER_NAME='quobyte-csi-testing'
TEST_CLUSTER_DIR='kind-cluster/kind-csi-testing'

echo ''
echo 'deleting kind images from docker'
docker rmi $(docker images -q | grep quobyte/kind-node-testing:v0)

if [[ -z "$(kind get clusters | grep ${CLUSTER_NAME})" ]]; then
  echo "Could not find cluster ${CLUSTER_NAME}"
  exit 1
fi

echo ''
echo 'deleting kind cluster'
kind delete cluster --name "$(kind get clusters | grep ${CLUSTER_NAME})"
rm -rf "${TEST_CLUSTER_DIR}"
exit 0
