apiVersion: v1
kind: Secret
metadata:
  name: quobyte-mount-secret
type: "kubernetes.io/quobyte"
data:
  # base64 encoded values of mount_access_key.csv
  accessKeyId: "MmRVbURINXpZbjM5UFlZUHJ1VUY="
  accessKeySecret: "djljeGpwci9KSnJ1RkhUQUROOUtNSHhjeWIxK3Q0SnFHanFSSEVwMA=="
