apiVersion: v1
kind: Secret
metadata:
  name: quobyte-admin-credentials
type: "kubernetes.io/quobyte"
data:
  # base64 encoded values of all_uses_access_key.csv
  accessKeyId: "UTRBaGowUHZVYlg1bjNmOGVjdlc="
  accessKeySecret: "cGFIaEphMjcvMVU3c1ZIbkoyVXErSjhBN1dmSzkvL2FQOTg5dXc0Lw=="
