apiVersion: v1
kind: Secret
metadata:
  name: quobyte-admin-credentials
type: "kubernetes.io/quobyte"
data:
  # base64 encoded values of all_uses_access_key.csv
  accessKeyId: "MVE2djZmemFCOXVxUTlNYlVyT0s="
  accessKeySecret: "MTMybXZlaGQ2Y0ZyWWlnL3pIV2ZYTFBwNmhxVzkrNGxCS29OSyt4aQ=="
