#!/bin/bash

KUBECONFIG="/etc/kubernetes/admin.conf"
NODES=1
# TODO(venkat): remove --short once it becomes the default with kubectl
K8S_VERSION="$(kubectl version --short | grep 'Server Version:' -m1 | cut -d":" -f2 | tr -d " ")"
STORAGE_CLASS=${STORAGE_CLASS:-$(pwd)/quobyte-csi/example/StorageClass.yaml}
SNAPSHOT_CLASS=${SNAPSHOT_CLASS:-$(pwd)/quobyte-csi/example/volume-snapshot-class.yaml}

# Requirements (manual)
# ----------------------
# 1. Quobyte CSI driver, clients with proper mountpoint and registry
# 2. CSI secret with proper data (API user and password)
# 3. Storage Class with proper tenant and tenant in storage cluster
# 4. Use IP for API URL to get around docker hostname to IP resolution issues on kubespray setups
# 5. Get ./log_collector and look logs after tests 


# TODO(venkat): Add "My Tenant" tenant and configure accessible network
# TODO(venkat): import access key and add it to secret
#sudo yum install -y wget git


#if [[ -d quobyte-csi ]]; then
#  rm -rf quobyte-csi
#fi

#git clone https://github.com/quobyte/quobyte-csi.git

# TODO(venkat): checkout specific commit
# TODO(venkat): setup clients, even better setup as part of vagrant setup
# cd quobyte-csi

# TODO(venkat): update driver (./quobyte-csi-driver/values.yaml)

# TODO(venkat) setup snapshots controller

if [[ -f /tmp/quobyte-csi-driver.yaml ]]; then
  rm /tmp/quobyte-csi-driver.yaml
fi
  
cat> /tmp/quobyte-csi-driver.yaml<<EOF
ShortName: quobyte-csi
StorageClass:
  FromFile: $STORAGE_CLASS
SnapshotClass:
  FromFile: $SNAPSHOT_CLASS
DriverInfo:
  Name: csi.quobyte.com
  # Add  new capabilites from here (sample for v1.18.5)
  # https://github.com/kubernetes/kubernetes/blob/e6503f8d8f769ace2f338794c914a96fc335df0f/test/e2e/storage/testsuites/testdriver.go#L137
  Capabilities:
    persistence: true
    fsGroup: false
    exec: true
    multipods: true
    controllerExpansion: true
    nodeExpansion: false
    singleNodeVolume: true
    snapshotDataSource: false
    RWX: true
EOF

if [[ -d kubernetes ]]; then
 rm -rf kubernetes
fi

K8S_TARBALL="kubernetes-test-linux-amd64.tar"
K8S_ZIP="${K8S_TARBALL}.gz"

if [[ -f ${K8S_ZIP} ]]; then
  rm ${K8S_ZIP}
fi

if [[ -f "${K8S_TARBALL}" ]]; then 
  rm "${K8S_TARBALL}"
fi

if [[ -f tests.txt ]]; then
  rm "tests.txt"
fi

wget -q https://storage.googleapis.com/kubernetes-release/release/$K8S_VERSION/${K8S_ZIP} \
&& gunzip kubernetes-test-linux-amd64.tar.gz && tar -xvf kubernetes-test-linux-amd64.tar \
&& kubernetes/test/bin/ginkgo -nodes=$NODES -focus='External.Storage.*csi.quobyte.com.*' \
-skip='\[Disruptive\]' \
kubernetes/test/bin/e2e.test -- -storage.testdriver=/tmp/quobyte-csi-driver.yaml -kubeconfig="${KUBECONFIG}" 2>&1 | tee tests.txt

