apiVersion: v1
kind: Secret
metadata:
  name: quobyte-admin-credentials
type: "kubernetes.io/quobyte"
data:
  # base64 encoded values of all_uses_access_key.csv
  accessKeyId: "YjdoNlRTczQ3Wk50QmZySEhoakg="
  accessKeySecret: "TVNRci9mUmZwalROSmp3ck5ZS2FzMVhTOVEvZVYvTmY4VWpuQW5jSA=="
