#!/bin/bash

echo 'reseting kubeadm'
sudo kubeadm reset -f

echo ''
echo 'stop kubelet and deleting related directories'
sudo systemctl stop kubelet
# sudo systemctl stop docker
sudo rm -rfv /etc/cni /var/lib/cni/ /etc/kubernetes /var/lib/dockershim /var/lib/etcd /var/lib/kubelet /var/run/kubernetes ~/.kube/*

echo ''
echo 'deleting docker entities'
sudo docker rm $(docker ps -a -q)
sudo docker volume rm $(docker volume ls -q)
docker rmi $(docker images -q | grep quobyte/kind-node-testing:v0)

echo ''
echo 'reseting iptables'
sudo iptables -F && sudo iptables -X
sudo iptables -t nat -F && sudo iptables -t nat -X
sudo iptables -t raw -F && sudo iptables -t raw -X
sudo iptables -t mangle -F && sudo iptables -t mangle -X

echo ''
echo 'restarting docker'
sudo systemctl restart docker

echo ''
echo 'deleting kind cluster'
kind delete cluster --name $(kind get clusters | grep quobyte-csi-experiment-testing) 

echo ''
echo 'deleting cluster directory'
rm -rf ./kind-csi-experiment-testing-corp

exit 0