#!/bin/bash

KUBECONFIG=${KUBECONFIG:-"/etc/kubernetes/admin.conf"}
NODES=1
# Note that you need to point kubeconfig correctly, otherwise kubectl cannot list sever version
K8S_VERSION="$(kubectl version | grep 'Server Version:' -m1 | cut -d":" -f2 | tr -d " ")"
STORAGE_CLASS=${STORAGE_CLASS:-$(pwd)/quobyte-csi/example/StorageClass.yaml}
SNAPSHOT_CLASS=${SNAPSHOT_CLASS:-''}
E2E_TEST_CONFIG_PATH='/tmp/quobyte-csi-driver.yaml'
CSI_PROVISIONER_NAME=${CSI_PROVISIONER_NAME:-'csi.quobyte.com'}
TESTS_LOGS_PATH='/tmp/test.txt'

cd /tmp

if [[ "$ENABLE_SNAPSHOTS" -eq 'true' && -z "$SNAPSHOT_CLASS" ]]; then
  echo "Missing volume snapshot class in test config"
fi

if [[ -f "$E2E_TEST_CONFIG_PATH" ]]; then
  rm "$E2E_TEST_CONFIG_PATH"
fi
  
cat> "$E2E_TEST_CONFIG_PATH"<<EOF
ShortName: quobyte-csi
StorageClass:
  FromFile: $STORAGE_CLASS
SnapshotClass:
  FromFile: $SNAPSHOT_CLASS
DriverInfo:
  Name: $CSI_PROVISIONER_NAME
  # Add  new capabilites from here (sample for v1.18.5)
  # https://github.com/kubernetes/kubernetes/blob/e6503f8d8f769ace2f338794c914a96fc335df0f/test/e2e/storage/testsuites/testdriver.go#L137
  Capabilities:
    persistence: true
    fsGroup: false
    exec: true
    multipods: true
    controllerExpansion: true
    nodeExpansion: false
    singleNodeVolume: true
    snapshotDataSource: $ENABLE_SNAPSHOTS
    RWX: true
    # Quobyte Snapshots live in <volume>/.snapshots/ cannot be moved from one volume to another.
    # So, cannot be moved from PVC (think of Quobyte volume equivalent) to another PVC in k8s. So disable the following test
    # https://github.com/kubernetes/kubernetes/blob/fbf1a0dc181ccbeb9925ad9c284d913a25c16562/test/e2e/storage/testsuites/provisioning.go#L454
    FSResizeFromSourceNotSupported: true
EOF

if [[ -d kubernetes ]]; then
 rm -rf kubernetes
fi

K8S_TARBALL="kubernetes-test-linux-amd64.tar"
K8S_ZIP="${K8S_TARBALL}.gz"

if [[ -f ${K8S_ZIP} ]]; then
  rm ${K8S_ZIP}
fi

if [[ -f "${K8S_TARBALL}" ]]; then 
  rm "${K8S_TARBALL}"
fi

if [[ -f "$TESTS_LOGS_PATH" ]]; then
  rm "$TESTS_LOGS_PATH"
fi

echo "Running E2E with test configuration $E2E_TEST_CONFIG_PATH"
echo "E2E test results can be found at $TESTS_LOGS_PATH on test running host"

echo -e "\e[33mNote:\e[0m If tests stuck, you need to check kind version and kind-cluster\n \
         base image compatibility. See ./run_test kindest/node:v1.... hash and kindest version\n \
         hash (kind requires exact hash specified in kind release). https://github.com/kubernetes-sigs/kind/releases"

wget https://storage.googleapis.com/kubernetes-release/release/$K8S_VERSION/${K8S_ZIP} \
&& gunzip kubernetes-test-linux-amd64.tar.gz && tar -xvf kubernetes-test-linux-amd64.tar --overwrite \
&& kubernetes/test/bin/ginkgo -nodes=$NODES -focus='External.Storage.*csi.quobyte.com.*' \
-skip='\[Disruptive\]' \
kubernetes/test/bin/e2e.test -- -storage.testdriver="$E2E_TEST_CONFIG_PATH" -kubeconfig="${KUBECONFIG}" 2>&1 | tee "$TESTS_LOGS_PATH"
