#!/bin/bash

KUBECONFIG=${KUBECONFIG:-"/etc/kubernetes/admin.conf"}
NODES=1
# Note that you need to point kubeconfig correctly, otherwise kubectl cannot list sever version
K8S_VERSION="$(kubectl version | grep 'Server Version:' -m1 | cut -d":" -f2 | tr -d " ")"
TEST_RUN_DIR=$(pwd)
STORAGE_CLASS=${STORAGE_CLASS:-$(pwd)/quobyte-csi/example/StorageClass.yaml}
SNAPSHOT_CLASS=${SNAPSHOT_CLASS:-''}
E2E_TEST_CONFIG_PATH='/tmp/quobyte-csi-driver.yaml'
CSI_PROVISIONER_NAME=${CSI_PROVISIONER_NAME:-'csi.quobyte.com'}
TESTS_LOGS_PATH='/tmp/test.txt'

KUBERNETES_SRC_DIR="${KUBERNETES_SRC_DIR:-/tmp/kubernetes}"

if [[ ! -d ${KUBERNETES_SRC_DIR} ]]; then
git clone https://github.com/kubernetes/kubernetes.git $KUBERNETES_SRC_DIR
fi

cd $KUBERNETES_SRC_DIR
git fetch --tags
git checkout tags/$K8S_VERSION
make WHAT=test/e2e/e2e.test
go install github.com/onsi/ginkgo/v2/ginkgo@latest

cd $TEST_RUN_DIR
cd /tmp

if [[ "$ENABLE_SNAPSHOTS" -eq 'true' && -z "$SNAPSHOT_CLASS" ]]; then
  echo "Missing volume snapshot class in test config"
fi

if [[ -f "$E2E_TEST_CONFIG_PATH" ]]; then
  rm "$E2E_TEST_CONFIG_PATH"
fi
  
cat> "$E2E_TEST_CONFIG_PATH"<<EOF
ShortName: quobyte-csi
StorageClass:
  FromFile: $STORAGE_CLASS
SnapshotClass:
  FromFile: $SNAPSHOT_CLASS
DriverInfo:
  Name: $CSI_PROVISIONER_NAME
  # Add  new capabilites from here (sample for v1.18.5)
  # https://github.com/kubernetes/kubernetes/blob/e6503f8d8f769ace2f338794c914a96fc335df0f/test/e2e/storage/testsuites/testdriver.go#L137
  Capabilities:
    persistence: true
    fsGroup: false
    exec: true
    multipods: true
    controllerExpansion: true
    nodeExpansion: false
    singleNodeVolume: true
    snapshotDataSource: $ENABLE_SNAPSHOTS
    RWX: true
EOF

echo "Running E2E with test configuration $E2E_TEST_CONFIG_PATH"
echo "E2E test results can be found at $TESTS_LOGS_PATH on test running host"

echo -e "\e[33mNote:\e[0m If tests stuck, you need to check kind version and kind-cluster\n \
         base image compatibility. See ./run_test kindest/node:v1.... hash and kindest version\n \
         hash (kind requires exact hash specified in kind release). https://github.com/kubernetes-sigs/kind/releases"

ginkgo -nodes=$NODES -focus='External.Storage.*csi.quobyte.com.*' \
-skip='\[Disruptive\]' \
$KUBERNETES_SRC_DIR/_output/local/go/bin/e2e.test -- -storage.testdriver="$E2E_TEST_CONFIG_PATH" -kubeconfig="${KUBECONFIG}" 2>&1 | tee "$TESTS_LOGS_PATH"
