#!/bin/bash

# Pre-requirements:
# valid ca.pem, client-cert.pem and client-key.pem files were added to working directory
# Docker, k8s, kind are installed and configured

MOUNT_WITH_ACCESS_KEYS=${MOUNT_WITH_ACCESS_KEYS:-n}
PATH="$(pwd):$PATH"
CODE_BASE_DIR="$(pwd)"
TEST_CLUSTER_DIR='kind-cluster/kind-csi-experiment-testing-corp'

if [ ! -z "$(git status --porcelain)" ]; then
  echo 'Requires clean directory (no stage/unstaged/untracked files) in repo'
  exit 1
fi

KIND_CLUSTER_NAME="quobyte-csi-experiment-testing"
# do not tag version as latest - that would trigger pull always from registry
CSI_DRIVER_VERSION="$(git rev-parse --short HEAD)"
# dummy.quobyte.com is not a docker registry. We buid docker image locally
# and make it available to kind nodes via 'kind load docker-image'
CSI_DRIVER_IMAGE="dummy.quobyte.com/quobyte-csi-driver:${CSI_DRIVER_VERSION}"
KUBECONFIG='/tmp/'

rm -rf "${TEST_CLUSTER_DIR}"

mkdir -p "${TEST_CLUSTER_DIR}"
cp kind-cluster/ca.pem kind-cluster/client-cert.pem kind-cluster/client-key.pem "${TEST_CLUSTER_DIR}"
cd "${TEST_CLUSTER_DIR}"

echo "Creating a Dockerfile * * * * * * * * *  * * * * * * * * * * * * * * * * *"
echo ""
echo ""
tee -a Dockerfile <<END
FROM kindest/node:v1.25.0
RUN apt-get -y update 
RUN apt-get -y install wget && apt-get install -y git && apt install -y nano
RUN groupadd -g 10001 nginx; useradd -u 10001 -g 10001 nginx
ENV CSI_DRIVER="quobyte"
ENV QUOBYTE_API_URL="http://testing-api.corp.quobyte.com:7860"
ENV QUOBYTE_REGISTRY="testing.corp.quobyte.com"
ENV CSI_PROVISIONER="csi.quobyte.com"
ENV QUOBYTE_MOUNT_POINT=/mnt/quobyte/mounts
ENV CSI_DRIVER_VERSION=$CSI_DRIVER_VERSION
ENV CSI_DRIVER_IMAGE=$CSI_DRIVER_IMAGE
ENV MOUNT_WITH_ACCESS_KEYS=$MOUNT_WITH_ACCESS_KEYS
END

echo "Building new image using the above Dockerfile. On the local machine: * * *"
# Change `v0` appropriately to whatever version is needed.
docker build -t 'quobyte/kind-node-testing:v0' -f Dockerfile .

docker image ls | grep 'quobyte/kind-node-testing:v0'

echo "Use the newly created image in the `kind` configuration: * * * * * * * * *"
tee -a kind-config-testing.yaml << END
kind: Cluster
name: ${KIND_CLUSTER_NAME}
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: quobyte/kind-node-testing:v0
  extraMounts:
    # mount codebase into container
    - hostPath: ${CODE_BASE_DIR}
      containerPath: /quobyte-csi
- role: worker
  image: quobyte/kind-node-testing:v0
- role: worker
  image: quobyte/kind-node-testing:v0
- role: worker
  image: quobyte/kind-node-testing:v0
END

echo  "Creating cluster with kind: * * * * * * * * * * * * * * * * * * * * * * *"
kind create cluster --config=./kind-config-testing.yaml

echo  "Labeling Kubernetes nodes * * * * * * * * * * * * * * * * * * * * * * * *"
for node in $(kubectl get nodes --no-headers | awk '{print $1}'); do
  kubectl label nodes $node quobyte_client="true"
done

echo "Building local csi driver image"
CODE_BASE_ROOT=${CODE_BASE_DIR} ${CODE_BASE_DIR}/src/build.sh
docker build -t ${CSI_DRIVER_IMAGE} -f ${CODE_BASE_DIR}/src/Dockerfile ${CODE_BASE_DIR}/src
if [[ "$?" -ne 0 ]]; then
  echo "Failed to create local image (compile or image build failed!)"
  exit 1
fi
kind load docker-image ${CSI_DRIVER_IMAGE} --name ${KIND_CLUSTER_NAME}

echo "creating and setting default namespace to quobyte * * * * * * * * * * * *" 
#to retrieve instances from all namespaces use '-A' argument
kubectl create ns quobyte
kubectl config get-contexts
kubectl get namespaces --context kind-quobyte-csi-experiment-testing
kubectl config use-context kind-quobyte-csi-experiment-testing
kubectl config set-context --current --namespace=quobyte

echo 'creating configmaps with required pem files'
kubectl -n kube-system create configmap quobyte-ca.pem --from-file=ca.pem
kubectl -n kube-system create configmap quobyte-cert.pem --from-file=client-cert.pem
kubectl -n kube-system create configmap quobyte-key.pem --from-file=client-key.pem

# chmod +x ../install_csi_3x ../pre-flight_checks
# docker cp ../install_csi_3x $(docker ps -aqf "name=control-plane"):/
# docker cp ../pre-flight_checks $(docker ps -aqf "name=control-plane"):/

#docker exec -it $(docker ps -aqf "name=control-plane") bash
