#!/bin/bash

# Pre-requirements:
# valid ca.pem, client-cert.pem and client-key.pem files were added to working directory
# Docker, k8s, kind are installed and configured
rm -rf  kind-csi-experiment-testing-corp

mkdir kind-csi-experiment-testing-corp
cp ca.pem client-cert.pem client-key.pem kind-csi-experiment-testing-corp
cd kind-csi-experiment-testing-corp

echo "Creating a Dockerfile * * * * * * * * *  * * * * * * * * * * * * * * * * *"
echo ""
echo ""
tee -a Dockerfile << END
FROM kindest/node:v1.23.6
RUN groupadd -g 10001 nginx; useradd -u 10001 -g 10001 nginx
ENV CSI_DRIVER="quobyte"
ENV QUOBYTE_API_URL="http://testing-api.corp.quobyte.com:7860"
ENV QUOBYTE_REGISTRY="testing.corp.quobyte.com"
ENV CSI_PROVISIONER="csi.quobyte.com"
ENV QUOBYTE_MOUNT_POINT=/mnt/quobyte/mounts
END

echo "Building new image using the above Dockerfile. On the local machine: * * *"
# Change `v0` appropriately to whatever version is needed.
docker build -t 'quobyte/kind-node-testing:v0' -f Dockerfile .

docker image ls | grep 'quobyte/kind-node-testing:v0'

echo "Use the newly created image in the `kind` configuration: * * * * * * * * *"
tee -a kind-config-testing.yaml << END
kind: Cluster
name: quobyte-csi-experiment-testing
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: quobyte/kind-node-testing:v0
- role: worker
  image: quobyte/kind-node-testing:v0
- role: worker
  image: quobyte/kind-node-testing:v0
- role: worker
  image: quobyte/kind-node-testing:v0
END

echo  "Creating cluster with kind: * * * * * * * * * * * * * * * * * * * * * * *"
kind create cluster --config=./kind-config-testing.yaml

echo  "Labeling Kubernetes nodes * * * * * * * * * * * * * * * * * * * * * * * *"
for node in $(kubectl get nodes --no-headers | awk '{print $1}'); do
  kubectl label nodes $node quobyte_client="true"
done

echo "creating and setting default namespace to quobyte * * * * * * * * * * * *" 
#to retrieve instances from all namespaces use '-A' argument
kubectl create ns quobyte
kubectl config get-contexts
kubectl get namespaces --context kind-quobyte-csi-experiment-testing
kubectl config use-context kind-quobyte-csi-experiment-testing
kubectl config set-context --current --namespace=quobyte

echo 'creating configmaps adding required access files'
kubectl -n quobyte create configmap quobyte-ca.pem --from-file=ca.pem
kubectl -n quobyte create configmap quobyte-cert.pem --from-file=client-cert.pem
kubectl -n quobyte create configmap quobyte-key.pem --from-file=client-key.pem

chmod +x ../install_csi_3x ../pre-flight_checks
docker cp ../install_csi_3x $(docker ps -aqf "name=control-plane"):/
docker cp ../pre-flight_checks $(docker ps -aqf "name=control-plane"):/


echo "logging in to the control plane by container ID * * * * * * * * * * * * * *"
docker exec -it $(docker ps -aqf "name=control-plane") bash