apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: quobyte-csi-psp
# provisioner must be csi.quobyte.com
provisioner: csi.quobyte.com
parameters:
  quobyteTenant: "My Tenant"
  # secret is used for dynamic volume provisioning.
  # The user credentials provided in this secret must have
  # volume create/delete permissions for `quobyteTenant` above.
  csiProvisionerSecretName: "quobyte-admin-credentials"
  csiProvisionerSecretNamespace: "quobyte"
  # Quobyte volume configuration
  quobyteConfig: "BASE"
  # creates quota for the volume if set to true. The size of the Quota
  # is the storage requested in PVC. If false, creates unrestricted size volume.  
  createQuota: "False"
  # volume root user. PodSecurityPolicy should be configured to propagate
  # access control into the pods.
  user: nginx
  # volume root group. PodSecurityPolicy should be configured to propagate
  # access control into the pods.
  group: nginx
  # volume access modes. PodSecurityPolicy should be configured to propagate
  # access control into the pods. It must be three digit value without '0' prefix.
  accessMode: "770"
reclaimPolicy: Retain
